import React from 'react';
import './../styles/Bio.css';
import Card from '@material-ui/core/Card';
import CardContent from '@material-ui/core/CardContent';
import Typography from '@material-ui/core/Typography';
import Chip from '@material-ui/core/Chip';


class Bio extends React.Component {


  render(){
    let interestChips = [];
    let interests = ['React', 'React Native', 'Interactive Mobile Development', 'GeoLocation', 'Mapping'];
       interestChips = interests.map((interest, index) => {
        return <Chip className='theme' color='primary'  key={index} label={interest} />
      });

    let skillsChips = [];
    let skills = ['Html', 'CSS', 'JavaScript', 'React.js', 'Redux', 'React Native', 'Firebase', 'Angular.js', 'RESTful routing', 'Google Maps API'];
    skillsChips = skills.map((skill, index) => {
     return <Chip className='theme' color='secondary'  key={index} label={skill} />
   });

    return(
      <div className='bio-style'>
        <header className='header'>
          About
        </header>
        <Card className='content-div'>
          <CardContent>
            <Typography variant='h3'>What I'm up to</Typography>
            <Typography variant='h5'>Currently I am student at Epicodus, specializing in <strong>Javascript</strong> and <strong>React</strong>. As a Junior Developer, I learn by being of service to the group.  I make the effort to prioritize test-driven development, and a focus on clear and concise code. Ultimately, I aim to combine my enjoyment of being part of a team and budding technical knowledge as I work towards becoming a mobile developer with React Native. I am inspired by projects such as <a href='https://www.native.io/industries/international_development'>these</a>.</Typography>
          </CardContent>
        </Card>
        <Card className='content-div'>
          <CardContent>
            <Typography variant='h3'>Previously</Typography>
            <Typography variant='h5'>I worked in Economic Development Researcher, as a recipient of a Fulbright Association grant.
  My research analyzed the distribution and investment of royalties generated by hydroelectric energy production within the state of Minas Gerais, Brazil.</Typography>
          </CardContent>
        </Card>
        <Card className='content-div'>
          <CardContent>
            <Typography variant='h3'>Interests</Typography>
            {interestChips}
          </CardContent>
        </Card>
        <Card className='content-div'>
          <CardContent>
            <Typography variant='h3'>Skills</Typography>
            {skillsChips}
          </CardContent>
        </Card>
      </div>
    );
  }
}


export default Bio;
