import React from 'react';
import './../styles/Bio.css';
import Card from '@material-ui/core/Card';
import CardContent from '@material-ui/core/CardContent';
import Typography from '@material-ui/core/Typography';
import Chip from '@material-ui/core/Chip';


class Bio extends React.Component {


  render(){
    let interestChips = [];
    let interests = ['JavaScript','React.js', 'React Native', 'Interactive Mobile Development', 'Angular.js', 'Consuming APIs', 'Decentralized Apps', 'Blockchain', 'Digital Cartography', 'Data Visualization', 'Agile'];
       interestChips = interests.map((interest, index) => {
        return <Chip className='theme' color='primary'  key={index} label={interest} />
      });

    let skillsChips = [];
    let skills = ['Html', 'CSS', 'JavaScript','C#', 'SQL', 'React', 'Redux', 'Firebase', 'Angular 4', 'Node / Express', 'Google Maps API', 'Leaflet.js', 'Mapbox', 'MongoDB', 'D3.js', 'Git'];
    skillsChips = skills.map((skill, index) => {
     return <Chip className='theme' color='secondary'  key={index} label={skill} />
   });

    return(
      <div className='bio-style'>
        <header className='header'>
          About
        </header>
        <Card className='content-div'>
          <CardContent>
            <Typography variant='h3'>What I'm up to</Typography>
            <Typography variant='h5'>Recently trained in web programming, specializing in <strong> C#</strong>,<strong> SQL</strong>,<strong> Javascript</strong> and <strong>React</strong>.  I am a passionate about data analysis and visualization. I enjoy consuming APIs and managing state with React and Redux. When I'm not calling on APIs, querying databases or mapping data, you can find me enjoying a grassy spot at the park, planting in the garden, and working in youth mentorship. I am inspired by projects such as <a href='https://www.native.io/industries/international_development'>this</a>, <a href='https://www.provenance.org/'>and this</a>. </Typography>
          </CardContent>
        </Card>
        <Card className='content-div'>
          <CardContent>
            <Typography variant='h3'>Previously</Typography>
            <Typography variant='h5'>I worked in Economic Development Research, as a recipient of Fulbright Association grant.
  My research analyzed the distribution and investment of royalties generated by hydroelectric energy production within the state of Minas Gerais, Brazil.  More recently, I worked in the field of community and youth development.  I was driven to learn software programming by my interest in data analysis and visualization.</Typography>
          </CardContent>
        </Card>
        <Card className='content-div'>
          <CardContent>
            <Typography variant='h3'>Interests</Typography>
            {interestChips}
          </CardContent>
        </Card>
        <Card className='content-div'>
          <CardContent>
            <Typography variant='h3'>Skills</Typography>
            {skillsChips}
          </CardContent>
        </Card>
      </div>
    );
  }
}


export default Bio;
